/* DO NOT MODIFY --- generated by ../../tools/logdef.pl from logdef.dat 
                     on Fri Jul  8 11:47:59 2011

<std-header orig-src='shore' genfile='true'>

SHORE -- Scalable Heterogeneous Object REpository

Copyright (c) 1994-99 Computer Sciences Department, University of
                      Wisconsin -- Madison
All Rights Reserved.

Permission to use, copy, modify and distribute this software and its
documentation is hereby granted, provided that both the copyright
notice and this permission notice appear in all copies of the
software, derivative works or modified versions, and any portions
thereof, and that both notices appear in supporting documentation.

THE AUTHORS AND THE COMPUTER SCIENCES DEPARTMENT OF THE UNIVERSITY
OF WISCONSIN - MADISON ALLOW FREE USE OF THIS SOFTWARE IN ITS
"AS IS" CONDITION, AND THEY DISCLAIM ANY LIABILITY OF ANY KIND
FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.

This software was developed with support by the Advanced Research
Project Agency, ARPA order number 018 (formerly 8230), monitored by
the U.S. Army Research Laboratory under contract DAAB07-91-C-Q518.
Further funding for this work was provided by DARPA through
Rome Research Laboratory Contract No. F30602-97-2-0247.

*/

#include "w_defines.h"

/*  -- do not edit anything above this line --   </std-header>*/


rc_t log_comment(const char* msg)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_comment));
        new (logrec) comment_log(msg);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_compensate(const lsn_t& rec_lsn)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_compensate));
        new (logrec) compensate_log(rec_lsn);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_abort()
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_abort));
        new (logrec) xct_abort_log();
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_freeing_space()
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_freeing_space));
        new (logrec) xct_freeing_space_log();
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_end()
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_end));
        new (logrec) xct_end_log();
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_end_group(const xct_t** l, int llen)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_end_group));
        new (logrec) xct_end_group_log(l, llen);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_prepare_st(const gtid_t* g, const server_handle_t& h)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_prepare_st));
        new (logrec) xct_prepare_st_log(g, h);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_prepare_lk(int num, lock_mode_t mode, lockid_t* lks)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_prepare_lk));
        new (logrec) xct_prepare_lk_log(num, mode, lks);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_prepare_alk(int num, lockid_t* lks, lock_mode_t* modes)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_prepare_alk));
        new (logrec) xct_prepare_alk_log(num, lks, modes);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_prepare_stores(int num, const stid_t* stids)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_prepare_stores));
        new (logrec) xct_prepare_stores_log(num, stids);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_xct_prepare_fi(int numex, int numix, int numsix, int numextent, const lsn_t& first, int rsvd, int ready, int used)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_xct_prepare_fi));
        new (logrec) xct_prepare_fi_log(numex, numix, numsix, numextent, first, rsvd, ready, used);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_alloc_file_page(const lpid_t& pid, const lsn_t& rec_lsn)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 2.4 
        W_DO(xd->get_logbuf(logrec, t_alloc_file_page));
        new (logrec) alloc_file_page_log(pid, rec_lsn);
        W_DO(xd->give_logbuf(logrec));
    }
    return RCOK;
}
rc_t log_alloc_pages_in_ext(const page_p& page, snum_t snum, extnum_t idx, const Pmap& pmap)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_alloc_pages_in_ext, &page));
        new (logrec) alloc_pages_in_ext_log(page, snum, idx, pmap);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_free_pages_in_ext(const page_p& page, snum_t snum, extnum_t idx, const Pmap& pmap)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.5 
        W_DO(xd->get_logbuf(logrec, t_free_pages_in_ext, &page));
        new (logrec) free_pages_in_ext_log(page, snum, idx, pmap);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_create_ext_list(const page_p& page, const stid_t& stid, extnum_t prev, extnum_t next, extnum_t count, const extnum_t* list)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_create_ext_list, &page));
        new (logrec) create_ext_list_log(page, stid, prev, next, count, list);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_free_ext_list(const page_p& page, const stid_t& stid, extnum_t head, extnum_t count)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_free_ext_list, &page));
        new (logrec) free_ext_list_log(page, stid, head, count);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_set_ext_next(const page_p& page, extnum_t ext, extnum_t new_next)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_set_ext_next, &page));
        new (logrec) set_ext_next_log(page, ext, new_next);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_store_operation(const page_p& page, const store_operation_param& op)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled;
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_store_operation, &page));
        new (logrec) store_operation_log(page, op);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_link(const page_p& page, shpid_t new_prev, shpid_t new_next)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_link, &page));
        new (logrec) page_link_log(page, new_prev, new_next);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_insert(const page_p& page, int idx, int cnt, const cvec_t* vec)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_insert, &page));
        new (logrec) page_insert_log(page, idx, cnt, vec);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_remove(const page_p& page, int idx, int cnt)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_remove, &page));
        new (logrec) page_remove_log(page, idx, cnt);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_format(const page_p& page, int idx, int cnt, const cvec_t* vec)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.22 
        W_DO(xd->get_logbuf(logrec, t_page_format, &page));
        new (logrec) page_format_log(page, idx, cnt, vec);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_mark(const page_p& page, int idx)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.1 
        W_DO(xd->get_logbuf(logrec, t_page_mark, &page));
        new (logrec) page_mark_log(page, idx);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_reclaim(const page_p& page, int idx, const cvec_t& vec)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.67 
        W_DO(xd->get_logbuf(logrec, t_page_reclaim, &page));
        new (logrec) page_reclaim_log(page, idx, vec);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_shift(const page_p& page, int idx2, page_s::slot_length_t off2, page_s::slot_length_t len2, int idx1, page_s::slot_length_t off1)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_shift, &page));
        new (logrec) page_shift_log(page, idx2, off2, len2, idx1, off1);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_splice(const page_p& page, int idx, int start, int len, const cvec_t& vec)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.18 
        W_DO(xd->get_logbuf(logrec, t_page_splice, &page));
        new (logrec) page_splice_log(page, idx, start, len, vec);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_splicez(const page_p& page, int idx, int start, int len, int osave, int nsave, const cvec_t& vec)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_splicez, &page));
        new (logrec) page_splicez_log(page, idx, start, len, osave, nsave, vec);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_set_byte(const page_p& page, int idx, u_char old, u_char bits, int op)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_page_set_byte, &page));
        new (logrec) page_set_byte_log(page, idx, old, bits, op);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_page_image(const page_p& page)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 0.0 
        W_DO(xd->get_logbuf(logrec, t_page_image, &page));
        new (logrec) page_image_log(page);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_btree_purge(const page_p& page)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 3.29 
        W_DO(xd->get_logbuf(logrec, t_btree_purge, &page));
        new (logrec) btree_purge_log(page);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_btree_insert(const page_p& page, int idx, const cvec_t& key, const cvec_t& el, bool unique)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.42 
        W_DO(xd->get_logbuf(logrec, t_btree_insert, &page));
        new (logrec) btree_insert_log(page, idx, key, el, unique);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_btree_remove(const page_p& page, int idx, const cvec_t& key, const cvec_t& el, bool unique)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 2.91 
        W_DO(xd->get_logbuf(logrec, t_btree_remove, &page));
        new (logrec) btree_remove_log(page, idx, key, el, unique);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_rtree_insert(const page_p& page, int idx, const nbox_t& key, const cvec_t& el)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_rtree_insert, &page));
        new (logrec) rtree_insert_log(page, idx, key, el);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
rc_t log_rtree_remove(const page_p& page, int idx, const nbox_t& key, const cvec_t& el)
{
    xct_t* xd = xct();
    bool should_log = smlevel_1::log && smlevel_0::logging_enabled
			&& (page.get_store_flags() & page.st_tmp) == 0
			&& xd && xd->is_log_on();
    if (should_log)  {
        logrec_t* logrec;
 // fudge 1.0 
        W_DO(xd->get_logbuf(logrec, t_rtree_remove, &page));
        new (logrec) rtree_remove_log(page, idx, key, el);
        W_DO(xd->give_logbuf(logrec, &page));
    }
    else page.set_dirty();
    return RCOK;
}
